#include <commands/solve.h>

CmdSolve::CmdSolve()
: Command({"solve", "s"}, "Resolve a catastrophe generated by 'generate' command")
{
}

void CmdSolve::execute(class Interpreter& interpreter, std::vector<std::string>& args) const
{
}